import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Toaster } from 'sonner';

import { AuthGuard } from '@/app/components/auth-guard';
import { Sidebar } from '@/app/components/sidebar';
import '@/app/globals.css';
import { TooltipProvider } from '@/components/ui/tooltip';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'VetAI - Veterinary AI Assistant',
  description: 'Generated by create next app',
};

export default function PrivateLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='pt-br' suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 dark:bg-slate-900`}
      >
        <AuthGuard>
          <TooltipProvider>
            <div className='flex h-screen overflow-hidden'>
              <Sidebar />
              <main className='flex-1 overflow-y-auto p-6 bg-gray-50 dark:bg-slate-900'>
                {children}
              </main>
            </div>
          </TooltipProvider>
        </AuthGuard>
        <Toaster position='top-right' richColors />
      </body>
    </html>
  );
}
